In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import (
    StandardScaler,
    MinMaxScaler,
    LabelEncoder
)
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import IsolationForest

In [9]:
df = pd.read_csv(r"C:\Users\prati\Downloads\Data Trasformation\adult_with_headers.csv")

In [10]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [12]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [13]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [14]:
print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [15]:
df.replace("?", np.nan, inplace=True)

print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [16]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print("\nNumerical Columns:", list(num_cols))
print("\nCategorical Columns:", list(cat_cols))

Numerical Columns: ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

Categorical Columns: ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'native_country', 'income']

In [17]:
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)


for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [18]:
standard_scaler = StandardScaler()
df_standard_scaled = df.copy()
df_standard_scaled[num_cols] = standard_scaler.fit_transform(df[num_cols])

In [19]:
minmax_scaler = MinMaxScaler()
df_minmax_scaled = df.copy()
df_minmax_scaled[num_cols] = minmax_scaler.fit_transform(df[num_cols])

In [20]:
print("""Several numerical features in the Adult dataset, such as age, education-num, and hours-per-week, follow approximately symmetric or moderately skewed distributions. These features are not bounded to a fixed range and represent continuous measurements.
When using linear models (Logistic Regression, Linear SVM) to predict income.
When applying distance-based algorithms where differences from the mean are important.
When performing dimensionality reduction techniques such as PCA.
In the Adult dataset:
Age values range roughly between 17 and 90.
Hours-per-week typically cluster around 40.
Standard scaling centers these features around zero, allowing the model to learn relationships without one feature dominating due to scale.
Standard scaling preserves the underlying distribution of these features while ensuring that no single numerical attribute disproportionately influences the model.

2. Min-Max Scaling 
Some numerical features in the Adult dataset, such as capital-gain and capital-loss, have extremely large ranges and are highly skewed. These features can negatively affect models that expect inputs within a limited range.
When training neural networks to predict income.
When using K-Nearest Neighbors or K-Means clustering.
When a bounded input range is required for faster and more stable training.
In the Adult dataset:
Capital-gain values range from 0 to very large numbers.
Min-Max scaling compresses these values into the [0,1] range, preventing extreme values from dominating distance calculations.
Min-Max scaling maintains relative differences while ensuring numerical stability for models sensitive to feature magnitude.

In the Adult Census Income dataset, Standard Scaling is preferred for features such as age, education-num, and hours-per-week because these variables are continuous and moderately distributed, making them suitable for models that rely on variance and distance from the mean. Min-Max Scaling is preferred for highly skewed features such as capital-gain and capital-loss, especially when training neural networks or distance-based models, as it constrains values within a fixed range and improves numerical stability.""")

Several numerical features in the Adult dataset, such as age, education-num, and hours-per-week, follow approximately symmetric or moderately skewed distributions. These features are not bounded to a fixed range and represent continuous measurements.
When using linear models (Logistic Regression, Linear SVM) to predict income.
When applying distance-based algorithms where differences from the mean are important.
When performing dimensionality reduction techniques such as PCA.
In the Adult dataset:
Age values range roughly between 17 and 90.
Hours-per-week typically cluster around 40.
Standard scaling centers these features around zero, allowing the model to learn relationships without one feature dominating due to scale.
Standard scaling preserves the underlying distribution of these features while ensuring that no single numerical attribute disproportionately influences the model.

2. Min-Max Scaling
Some numerical features in the Adult dataset, such as capital-gain and capital-loss, have extremely large ranges and are highly skewed. These features can negatively affect models that expect inputs within a limited range.
When training neural networks to predict income.
When using K-Nearest Neighbors or K-Means clustering.
When a bounded input range is required for faster and more stable training.
In the Adult dataset:
Capital-gain values range from 0 to very large numbers.
Min-Max scaling compresses these values into the [0,1] range, preventing extreme values from dominating distance calculations.
Min-Max scaling maintains relative differences while ensuring numerical stability for models sensitive to feature magnitude.

In the Adult Census Income dataset, Standard Scaling is preferred for features such as age, education-num, and hours-per-week because these variables are continuous and moderately distributed, making them suitable for models that rely on variance and distance from the mean. Min-Max Scaling is preferred for highly skewed features such as capital-gain and capital-loss, especially when training neural networks or distance-based models, as it constrains values within a fixed range and improves numerical stability.

In [28]:
low_cardinality = [col for col in cat_cols if df[col].nunique() < 5]
high_cardinality = [col for col in cat_cols if df[col].nunique() >= 5]

print("\nLow Cardinality Columns (<5 categories):", low_cardinality)
print("\nHigh Cardinality Columns (>=5 categories):", high_cardinality)
print("""We divided categorical features into:
Low-cardinality (< 5 categories)
High-cardinality (≥ 5 categories)""")

Low Cardinality Columns (<5 categories): ['sex', 'income']

High Cardinality Columns (>=5 categories): ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'native_country']
We divided categorical features into:
Low-cardinality (< 5 categories)
High-cardinality (≥ 5 categories)

In [38]:
df_ohe = pd.get_dummies(
    df,
    columns=low_cardinality,
    drop_first=True
)
print("""Applied One-Hot Encoding to categorical variables with fewer than 5 categories.
No ordinal relationship between categories
Prevents false ranking
Ideal for small category sets
Converts each category into a binary feature (0 or 1).
Pros
No assumption of order between categories
Safe for linear and distance-based models
Prevents ordinal bias
Cons
Increases number of features
Not suitable for high-cardinality variables
Can increase memory usage""")

Applied One-Hot Encoding to categorical variables with fewer than 5 categories.
No ordinal relationship between categories
Prevents false ranking
Ideal for small category sets
Converts each category into a binary feature (0 or 1).
Pros
No assumption of order between categories
Safe for linear and distance-based models
Prevents ordinal bias
Cons
Increases number of features
Not suitable for high-cardinality variables
Can increase memory usage

In [37]:
df_encoded = df_ohe.copy()
label_encoder = LabelEncoder()

for col in high_cardinality:
    df_encoded[col] = label_encoder.fit_transform(df_encoded[col])
print("""Applied Label Encoding to variables with more than 5 categories.
One-Hot Encoding would create too many columns
Label Encoding is memory-efficient
Suitable for tree-based models
Maps each category to a unique numerical value.
Pros
Memory efficient
Works well for tree-based models
Simple and fast
Cons
Introduces false ordering
Not suitable for linear models unless handled carefully""")

Applied Label Encoding to variables with more than 5 categories.
One-Hot Encoding would create too many columns
Label Encoding is memory-efficient
Suitable for tree-based models
Maps each category to a unique numerical value.
Pros
Memory efficient
Works well for tree-based models
Simple and fast
Cons
Introduces false ordering
Not suitable for linear models unless handled carefully

In [40]:
#Feature 1: Work Intensity
df_encoded['work_intensity'] = (
    df_encoded['hours_per_week'] / (df_encoded['age'] + 1)
)

# Feature 2: Education per Age
df_encoded['education_per_age'] = (
    df_encoded['education_num'] / (df_encoded['age'] + 1)
)
print(""""Created a feature combining age and working hours.
Raw features may not fully capture behavior.
This feature represents effort relative to age.
Provides deeper insight into work patterns linked to income.
Feature 2: Education per Age
Created a feature combining education level and age.
Helps identify individuals who achieved higher education earlier.
Improves the model’s ability to differentiate income levels.
""")

"Created a feature combining age and working hours.
Raw features may not fully capture behavior.
This feature represents effort relative to age.
Provides deeper insight into work patterns linked to income.
Feature 2: Education per Age
Created a feature combining education level and age.
Helps identify individuals who achieved higher education earlier.
Improves the model’s ability to differentiate income levels.

In [35]:
df_encoded['capital_gain_log'] = np.log1p(df_encoded['capital_gain'])
print("""Transformation of Skewed Numerical Feature
Applied a log transformation to the capital-gain feature.
Capital gain is highly skewed
Extreme values distort model learning
Log transformation stabilizes variance
Reduces skewness
Makes distribution more normal
Improves model performance""")

Transformation of Skewed Numerical Feature
Applied a log transformation to the capital-gain feature.
Capital gain is highly skewed
Extreme values distort model learning
Log transformation stabilizes variance
Reduces skewness
Makes distribution more normal
Improves model performance

In [32]:
X = df_encoded.drop('income_>50K', axis=1, errors='ignore')

# Isolation Forest
iso_forest = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)

iso_forest.fit(X)

# Get anomaly scores
anomaly_scores = iso_forest.decision_function(X)

# Add anomaly score to dataset
df_encoded['anomaly_score'] = anomaly_scores
print("""Detects outliers and rare patterns
Helps identify features contributing to anomalies
Improves robustness of feature selection""")

Detects outliers and rare patterns
Helps identify features contributing to anomalies
Improves robustness of feature selection

In [ ]:
import ppscore as pps
pps_scores = []

for col in df_encoded.columns:
    if col != 'income_>50K':
        score = pps.score(df_encoded, col, 'income_>50K')
        pps_scores.append(score)

pps_df = pd.DataFrame(pps_scores)
pps_df = pps_df.sort_values(by='ppscore', ascending=False)

In [39]:
print("""Measures predictive power (linear + non-linear)
Works with categorical and numerical features
Ranks features by importance for income prediction""")

Measures predictive power (linear + non-linear)
Works with categorical and numerical features
Ranks features by importance for income prediction

In [31]:
print("\nFinal Dataset Shape:", df_encoded.shape)
print("\nFinal Dataset Preview:")
print(df_encoded.head())

Final Dataset Shape: (32561, 15)

Final Dataset Preview:
   age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  capital_gain  capital_loss  hours_per_week  \
0           1             1     4          2174             0              40
1           4             0     4             0             0              13
2           6             1     4             0             0              40
3           6             0     2             0             0              40
4          10             5     2             0             0              40

   native_country  sex_ Male  income_ >50K
0              39       True         False
1              39       True         False
2              39       True         False
3              39       True         False
4               5      False         False